// swift-tools-version: 6.3

import PackageDescription

let package = Package(
    name: "CodeEdit",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v26),
    ],
    products: [
        .executable(
            name: "CodeEdit",
            targets: ["CodeEdit"]
        ),
    ],
    dependencies: [
        .package(path: "Packages/AboutWindow"),
        .package(path: "Packages/CodeEditHighlighting"),
        .package(path: "Packages/CodeEditLanguages"),
        .package(path: "Packages/CodeEditTextView"),
        .package(path: "Packages/CodeEditSyntaxDefinitions"),
        .package(path: "Packages/CodeEditSymbols"),
        .package(url: "https://github.com/ChimeHQ/ConcurrencyPlus", from: "0.4.1"),
        .package(url: "https://github.com/ChimeHQ/LanguageClient", from: "0.8.2"),
        .package(url: "https://github.com/ChimeHQ/LanguageServerProtocol", from: "0.13.2"),
        .package(url: "https://github.com/Flight-School/AnyCodable", from: "0.6.0"),
        .package(url: "https://github.com/groue/GRDB.swift.git", from: "6.0.0"),
        .package(url: "https://github.com/johnsundell/collectionconcurrencykit", from: "0.2.0"),
        .package(url: "https://github.com/apple/swift-async-algorithms.git", from: "1.0.0"),
        .package(url: "https://github.com/siteline/SwiftUI-Introspect.git", from: "1.2.0"),
        .package(url: "https://github.com/pointfreeco/swift-snapshot-testing.git", from: "1.17.6"),
        .package(url: "https://github.com/Wouter01/LogStream", from: "1.3.0"),
    ],
    targets: [
        .executableTarget(
            name: "CodeEdit",
            dependencies: [
                .product(name: "AboutWindow", package: "AboutWindow"),
                .product(name: "CodeEditHighlighting", package: "CodeEditHighlighting"),
                .product(name: "CodeEditLanguages", package: "CodeEditLanguages"),
                .product(name: "CodeEditTextView", package: "CodeEditTextView"),
                .product(name: "CodeEditSyntaxDefinitions", package: "CodeEditSyntaxDefinitions"),
                .product(name: "CodeEditSymbols", package: "CodeEditSymbols"),
                .product(name: "ConcurrencyPlus", package: "ConcurrencyPlus"),
                .product(name: "LanguageClient", package: "LanguageClient"),
                .product(name: "LanguageServerProtocol", package: "LanguageServerProtocol"),
                .product(name: "AnyCodable", package: "AnyCodable"),
                .product(name: "GRDB", package: "GRDB.swift"),
                .product(name: "CollectionConcurrencyKit", package: "collectionconcurrencykit"),
                .product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
                .product(name: "SwiftUIIntrospect", package: "SwiftUI-Introspect"),
                .product(name: "LogStream", package: "LogStream"),
            ],
            path: "CodeEdit",
            exclude: [
                "AppDelegate.swift",
                "CodeEdit.entitlements",
                "Info.plist",
                "Preview Content",
                "Features/ActivityViewer",
                "Features/CEWorkspace",
                "Features/CEWorkspaceSettings",
                "Features/CodeEditUI",
                "Features/Commands",
                "Features/Documents/Controllers",
                "Features/Documents/Indexer",
                "Features/Documents/WorkspaceDocument",
                "Features/Extensions",
                "Features/Feedback",
                "Features/InspectorArea",
                "Features/LSP",
                "Features/Editor/JumpBar",
                "Features/Editor/Models",
                "Features/Editor/TabBar",
                "Features/Editor/Views/EditorAreaFileView.swift",
                "Features/Editor/Views/EditorAreaView.swift",
                "Features/Editor/Views/EditorLayoutView.swift",
                "Features/Editor/Views/LoadingFileView.swift",
                "Features/NavigatorArea",
                "Features/Notifications",
                "Features/OpenQuickly",
                "Features/Search",
                "Features/Settings",
                "Features/SplitView",
                "Features/SourceControl",
                "Features/StatusBar",
                "Features/Tasks",
                "Features/UtilityArea",
                "Features/InspectorArea/Models/InspectorTab.swift",
                "WorkspaceSheets.swift",
                "WorkspaceView.swift",
                "Features/WindowCommands",
                "Features/WindowCommands/ExtensionCommands.swift",
                "Features/WindowCommands/EditorCommands.swift",
                "Features/Extensions/ExtensionDiscovery.swift",
                "Features/Extensions/ExtensionInfo.swift",
                "Features/Extensions/ExtensionSceneView.swift",
                "Features/Extensions/ExtensionsManager.swift",
                "Features/Extensions/ExtensionActivatorView.swift",
                "Features/Welcome",
                "ShellIntegration",
                "Utils/Compatibility",
                "Utils/DependencyInjection",
                "Utils/Environment",
                "Utils/Extensions/Date",
                "Utils/Extensions/LocalProcess",
                "Utils/Extensions/SemanticToken",
                "Utils/Extensions/TextView",
                "Utils/Extensions/URL"
            ],
            resources: [
                .process("Assets.xcassets"),
                .process("Features/Keybindings/default_keybindings.json"),
            ]
        ),
        .testTarget(
            name: "CodeEditTests",
            dependencies: [
                "CodeEdit",
                .product(name: "SnapshotTesting", package: "swift-snapshot-testing"),
            ],
            path: "CodeEditTests",
            sources: [
                "PackageSmoke/CodeFileDocumentLifecycleTests.swift"
            ]
        ),
    ]
)
